"""empty message

Revision ID: 17e961b5d86
Revises: 1e81425c4d7a
Create Date: 2015-05-21 01:02:17.119228

"""

# revision identifiers, used by Alembic.
revision = '17e961b5d86'
down_revision = '1e81425c4d7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_uploads', sa.Column('data', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_uploads', 'data')
    ### end Alembic commands ###
