"""empty message

Revision ID: 18d4fb926602
Revises: 1b3f88773db7
Create Date: 2015-05-20 22:14:25.467547

"""

# revision identifiers, used by Alembic.
revision = '18d4fb926602'
down_revision = '1b3f88773db7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('path', sa.Unicode(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_uploads')
    ### end Alembic commands ###
