"""empty message

Revision ID: 1addce067dcb
Revises: 3979de75f416
Create Date: 2015-03-05 21:54:52.820399

"""

# revision identifiers, used by Alembic.
revision = '1addce067dcb'
down_revision = '3979de75f416'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapoints', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datapoints', 'datasets', ['dataset_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datapoints', type_='foreignkey')
    op.drop_column('datapoints', 'dataset_id')
    ### end Alembic commands ###
