"""empty message

Revision ID: 1e81425c4d7a
Revises: 18d4fb926602
Create Date: 2015-05-20 22:29:42.857984

"""

# revision identifiers, used by Alembic.
revision = '1e81425c4d7a'
down_revision = '18d4fb926602'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_uploads', sa.Column('filename', sa.Unicode(), nullable=True))
    op.drop_column('study_uploads', 'path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_uploads', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('study_uploads', 'filename')
    ### end Alembic commands ###
