"""empty message

Revision ID: 1ebc48d7f36
Revises: 3db6e7d42790
Create Date: 2015-03-06 21:55:43.021121

"""

# revision identifiers, used by Alembic.
revision = '1ebc48d7f36'
down_revision = '3db6e7d42790'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapoints', sa.Column('selected', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datapoints', 'selected')
    ### end Alembic commands ###
