"""empty message

Revision ID: 2289e585ec7b
Revises: 4291771faa57
Create Date: 2016-02-29 01:54:50.285413

"""

# revision identifiers, used by Alembic.
revision = '2289e585ec7b'
down_revision = '4291771faa57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sz_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sz_job_study_id'), 'sz_job', ['study_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sz_job_study_id'), table_name='sz_job')
    op.drop_table('sz_job')
    ### end Alembic commands ###
