"""empty message

Revision ID: 26e53776a065
Revises: 48ca5bd2ad9e
Create Date: 2015-05-26 20:06:36.206872

"""

# revision identifiers, used by Alembic.
revision = '26e53776a065'
down_revision = '48ca5bd2ad9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datapoints_dataset_id'), 'datapoints', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_datapoints_timestamp'), 'datapoints', ['timestamp'], unique=False)
    op.create_index(op.f('ix_datasets_study_id'), 'datasets', ['study_id'], unique=False)
    op.create_index(op.f('ix_notes_dataset_id'), 'notes', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_study_uploads_study_id'), 'study_uploads', ['study_id'], unique=False)
    op.create_index(op.f('ix_study_users_study_id'), 'study_users', ['study_id'], unique=False)
    op.create_index(op.f('ix_study_users_user_id'), 'study_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_labels_datapoint_id'), 'user_labels', ['datapoint_id'], unique=False)
    op.create_index(op.f('ix_user_labels_dataset_id'), 'user_labels', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_user_labels_user_id'), 'user_labels', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_labels_user_id'), table_name='user_labels')
    op.drop_index(op.f('ix_user_labels_dataset_id'), table_name='user_labels')
    op.drop_index(op.f('ix_user_labels_datapoint_id'), table_name='user_labels')
    op.drop_index(op.f('ix_study_users_user_id'), table_name='study_users')
    op.drop_index(op.f('ix_study_users_study_id'), table_name='study_users')
    op.drop_index(op.f('ix_study_uploads_study_id'), table_name='study_uploads')
    op.drop_index(op.f('ix_notes_dataset_id'), table_name='notes')
    op.drop_index(op.f('ix_datasets_study_id'), table_name='datasets')
    op.drop_index(op.f('ix_datapoints_timestamp'), table_name='datapoints')
    op.drop_index(op.f('ix_datapoints_dataset_id'), table_name='datapoints')
    ### end Alembic commands ###
