"""empty message

Revision ID: 2b231c9bef13
Revises: None
Create Date: 2015-04-15 17:45:08.938484

"""

# revision identifiers, used by Alembic.
revision = '2b231c9bef13'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapoints', sa.Column('training', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datapoints', 'training')
    ### end Alembic commands ###
