"""empty message

Revision ID: 3042dc05882
Revises: 4952e3c0b0a8
Create Date: 2015-03-04 23:21:15.992063

"""

# revision identifiers, used by Alembic.
revision = '3042dc05882'
down_revision = '4952e3c0b0a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('title', sa.Unicode(), nullable=True))
    op.drop_column('datasets', 'timestamp')
    op.drop_column('datasets', 'value')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('datasets', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('datasets', 'title')
    ### end Alembic commands ###
