"""empty message

Revision ID: 33578d0361f7
Revises: 4c02554712f1
Create Date: 2015-05-17 21:57:15.058360

"""

# revision identifiers, used by Alembic.
revision = '33578d0361f7'
down_revision = '4c02554712f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
