"""empty message

Revision ID: 3510e6db4bdd
Revises: 553bd790f659
Create Date: 2016-02-29 02:27:22.745419

"""

# revision identifiers, used by Alembic.
revision = '3510e6db4bdd'
down_revision = '553bd790f659'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sz_job', sa.Column('csv_blob', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sz_job', 'csv_blob')
    ### end Alembic commands ###
