"""empty message

Revision ID: 371b8b747fb9
Revises: 5534aaacefa2
Create Date: 2015-05-27 13:42:30.506442

"""

# revision identifiers, used by Alembic.
revision = '371b8b747fb9'
down_revision = '5534aaacefa2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labelled_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labelled_datasets_dataset_id'), 'labelled_datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_labelled_datasets_user_id'), 'labelled_datasets', ['user_id'], unique=False)
    op.drop_column(u'datasets', 'labelled')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'datasets', sa.Column('labelled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_labelled_datasets_user_id'), table_name='labelled_datasets')
    op.drop_index(op.f('ix_labelled_datasets_dataset_id'), table_name='labelled_datasets')
    op.drop_table('labelled_datasets')
    ### end Alembic commands ###
