"""empty message

Revision ID: 389e90029cfa
Revises: 17e961b5d86
Create Date: 2015-05-21 08:07:03.355168

"""

# revision identifiers, used by Alembic.
revision = '389e90029cfa'
down_revision = '17e961b5d86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datapoint_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['datapoint_id'], ['datapoints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'datapoints', 'selected')
    op.add_column(u'users', sa.Column('stormpath_id', sa.Unicode(), nullable=True))
    op.drop_column(u'users', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column(u'users', 'stormpath_id')
    op.add_column(u'datapoints', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('user_labels')
    ### end Alembic commands ###
