"""empty message

Revision ID: 38bec17a4af2
Revises: 26e53776a065
Create Date: 2015-05-26 20:22:34.771472

"""

# revision identifiers, used by Alembic.
revision = '38bec17a4af2'
down_revision = '26e53776a065'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
