"""empty message

Revision ID: 3979de75f416
Revises: 3042dc05882
Create Date: 2015-03-05 21:40:49.627982

"""

# revision identifiers, used by Alembic.
revision = '3979de75f416'
down_revision = '3042dc05882'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datapoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('datapoints')
    ### end Alembic commands ###
