"""empty message

Revision ID: 39b3ee90f7be
Revises: 96ad9704add
Create Date: 2015-05-17 23:32:31.177640

"""

# revision identifiers, used by Alembic.
revision = '39b3ee90f7be'
down_revision = '96ad9704add'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
