"""empty message

Revision ID: 3c0b34e819dc
Revises: 4cdc91d06869
Create Date: 2015-05-21 11:07:24.055686

"""

# revision identifiers, used by Alembic.
revision = '3c0b34e819dc'
down_revision = '4cdc91d06869'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
