"""empty message

Revision ID: 3db6e7d42790
Revises: 46b6084fd26d
Create Date: 2015-03-06 19:06:06.499308

"""

# revision identifiers, used by Alembic.
revision = '3db6e7d42790'
down_revision = '46b6084fd26d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('owner', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'datasets', sa.Column('study_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datasets', 'studies', ['study_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column(u'datasets', 'study_id')
    op.drop_table('studies')
    ### end Alembic commands ###
