"""empty message

Revision ID: 45d6c7bf650c
Revises: 17699fea4340
Create Date: 2015-05-27 16:31:06.367143

"""

# revision identifiers, used by Alembic.
revision = '45d6c7bf650c'
down_revision = '17699fea4340'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('y_max', sa.Float(), nullable=True))
    op.add_column('studies', sa.Column('y_min', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'y_min')
    op.drop_column('studies', 'y_max')
    ### end Alembic commands ###
