"""empty message

Revision ID: 46ae5e506646
Revises: 3510e6db4bdd
Create Date: 2016-07-01 04:56:42.483972

"""

# revision identifiers, used by Alembic.
revision = '46ae5e506646'
down_revision = '3510e6db4bdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column(u'users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'password')
    op.drop_column(u'users', 'confirmed_at')
    op.drop_column(u'users', 'active')
    op.drop_table('roles_users')
    op.drop_table('role')
    ### end Alembic commands ###
