"""empty message

Revision ID: 48c19e144a30
Revises: 1addce067dcb
Create Date: 2015-03-05 22:37:02.226737

"""

# revision identifiers, used by Alembic.
revision = '48c19e144a30'
down_revision = '1addce067dcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
