"""empty message

Revision ID: 48ca5bd2ad9e
Revises: 3c0b34e819dc
Create Date: 2015-05-26 18:24:01.952763

"""

# revision identifiers, used by Alembic.
revision = '48ca5bd2ad9e'
down_revision = '3c0b34e819dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_labels', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_labels', 'datasets', ['dataset_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_labels', type_='foreignkey')
    op.drop_column('user_labels', 'dataset_id')
    ### end Alembic commands ###
