"""empty message

Revision ID: 4952e3c0b0a8
Revises: f3d2dff0d76
Create Date: 2015-03-04 23:15:51.850165

"""

# revision identifiers, used by Alembic.
revision = '4952e3c0b0a8'
down_revision = 'f3d2dff0d76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    ### end Alembic commands ###
