"""empty message

Revision ID: 4c02554712f1
Revises: 1ebc48d7f36
Create Date: 2015-04-29 21:39:00.511961

"""

# revision identifiers, used by Alembic.
revision = '4c02554712f1'
down_revision = '1ebc48d7f36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapoints', sa.Column('training', sa.Boolean(), nullable=True))
    op.add_column('datasets', sa.Column('labelled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'labelled')
    op.drop_column('datapoints', 'training')
    ### end Alembic commands ###
