"""empty message

Revision ID: 4cdc91d06869
Revises: 389e90029cfa
Create Date: 2015-05-21 08:15:26.516126

"""

# revision identifiers, used by Alembic.
revision = '4cdc91d06869'
down_revision = '389e90029cfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
