"""empty message

Revision ID: 50416b05c63e
Revises: 48c19e144a30
Create Date: 2015-03-05 22:40:33.449309

"""

# revision identifiers, used by Alembic.
revision = '50416b05c63e'
down_revision = '48c19e144a30'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    op.alter_column(
      table_name='datasets', 
      column_name='created_at', 
      type_=postgresql.TIMESTAMP(), 
      autoincrement=False, 
      nullable=True)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
