"""empty message

Revision ID: 553bd790f659
Revises: 2289e585ec7b
Create Date: 2016-02-29 02:14:57.098346

"""

# revision identifiers, used by Alembic.
revision = '553bd790f659'
down_revision = '2289e585ec7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sz_job', sa.Column('message', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sz_job', 'message')
    ### end Alembic commands ###
