"""empty message

Revision ID: 62bab0024fac
Revises: f71b10058f31
Create Date: 2016-07-03 02:59:30.861624

"""

# revision identifiers, used by Alembic.
revision = '62bab0024fac'
down_revision = 'f71b10058f31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('token', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'token')
    ### end Alembic commands ###
