"""empty message

Revision ID: 62c3c54fa19c
Revises: 56c689702a23
Create Date: 2016-07-22 05:26:11.016603

"""

# revision identifiers, used by Alembic.
revision = '62c3c54fa19c'
down_revision = '56c689702a23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sz_job', sa.Column('csv_binary_blob', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sz_job', 'csv_binary_blob')
    ### end Alembic commands ###
