"""empty message

Revision ID: f71b10058f31
Revises: 8ac91a55e860
Create Date: 2016-07-03 02:03:42.770593

"""

# revision identifiers, used by Alembic.
revision = 'f71b10058f31'
down_revision = '8ac91a55e860'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_uploads', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('study_uploads', sa.Column('state', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_uploads', 'state')
    op.drop_column('study_uploads', 'error_message')
    ### end Alembic commands ###
